// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6ra0R2A0afTcppk5gnNwGXE9fEXYWR4Q',
    appId: '1:916585431468:web:3f846c0d3c1d116183fa09',
    messagingSenderId: '916585431468',
    projectId: 'soko-v2-92f61',
    authDomain: 'soko-v2-92f61.firebaseapp.com',
    storageBucket: 'soko-v2-92f61.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSOmtxPJGRaqSIn9k_tp-VTk1ovFrnBfg',
    appId: '1:916585431468:android:f3e7dff1dd95685a83fa09',
    messagingSenderId: '916585431468',
    projectId: 'soko-v2-92f61',
    storageBucket: 'soko-v2-92f61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSWmPH8IQlVjcWQYzh9KsvJHqf7wPpy3E',
    appId: '1:916585431468:ios:ca62eaea3f433efd83fa09',
    messagingSenderId: '916585431468',
    projectId: 'soko-v2-92f61',
    storageBucket: 'soko-v2-92f61.appspot.com',
    iosBundleId: 'com.example.sokoV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSWmPH8IQlVjcWQYzh9KsvJHqf7wPpy3E',
    appId: '1:916585431468:ios:ca62eaea3f433efd83fa09',
    messagingSenderId: '916585431468',
    projectId: 'soko-v2-92f61',
    storageBucket: 'soko-v2-92f61.appspot.com',
    iosBundleId: 'com.example.sokoV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6ra0R2A0afTcppk5gnNwGXE9fEXYWR4Q',
    appId: '1:916585431468:web:2b384539713495b283fa09',
    messagingSenderId: '916585431468',
    projectId: 'soko-v2-92f61',
    authDomain: 'soko-v2-92f61.firebaseapp.com',
    storageBucket: 'soko-v2-92f61.appspot.com',
  );
}
